### ISSUE TITLE
提一些建议

### ISSUE THREAD

**Issue by bosens-China** [liyao1520/vitepress-demo-editor#1]
1. 不要使用可编辑的这种形式，默认编辑器放到右边很丑；
2. 如果有编辑需求可以参考antd把代码放到外部的web编辑器；
3. 可以支持直接src ./index.vue 的这种形式
4. 默认代码收起来，点击隐藏

**Comment by liyao1520** [comment]
非常感谢建议，有时间会新增功能

以下写法可以上下显示，并且支持显示隐藏代码

方式1
:::demo  column

:::

方式2
enhanceApp({ app }) {
    app.use(vuePlugin, {
      defaultDirection: "column", 
  },

**Comment by bosens-China** [comment]
老铁有没有兴趣一起搞一下项目。
我现在也在写组件库，不过发现生成文档的工具太少了
准备拓展一下vue press的主题，写一套类似antd风格的

**Comment by liyao1520** [comment]
抱歉，最近正准备秋招，要背八股文😭
